### PR TITLE
Boot strap ks

### PR DESCRIPTION
**Pull request by Khal-Shah**
Updated version (Feb 7).

### CODE REVIEW

**Comment by samgo1** [comment]
Make a PR to dev pls

**Comment by samgo1** [comment]
I see you added the simple_form gem as well, I have no problem with that but did you install it according to https://github.com/plataformatec/simple_form ?

**Comment by Khal-Shah** [comment]
I just tried the command: rails generate simple_form:install --bootstrap 
again and there were no new changes so everything should be there already.

**Review by samgo1 — APPROVED** [review]
good

**Pull request merged**
